apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vaporshifttest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vaporshifttest
    app.kubernetes.io/part-of: vaporshifttest
  name: vaporshifttest
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: vaporshifttest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: vaporshifttest
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-trees-tenant/vaporshifttest/vaporshifttest@sha256:a5460ccc3363e8a1842cf97e1616131bfb761fc7038bc781733c921754a6973c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
