apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vaporshifttest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vaporshifttest
    app.kubernetes.io/part-of: vaporshifttest
  name: vaporshifttest
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: vaporshifttest
status:
  loadBalancer: {}
