apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vaporshifttest
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-trees-tenant/vaporshifttest/vaporshifttest@sha256:d3e730d38ef887d9211f53cb24c1cb437aecf5cdb0600e092940fae6c0e75f53
        name: container-image
        resources: {}
status: {}
