apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vaporshifttest
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-trees-tenant/vaporshifttest/vaporshifttest@sha256:a5460ccc3363e8a1842cf97e1616131bfb761fc7038bc781733c921754a6973c
        name: container-image
        resources: {}
status: {}
